name: CI
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.14.x
          lhci autorun
      - name: Deploy to GitHub Pages
        if: success()
        run: |
          # Set up Git user
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git checkout --orphan gh-pages || git checkout gh-pages

          cp -R .lighthouseci/* .

          git add .
          git commit -m "Update Lighthouse CI reports"
          git push --force origin gh-pages