name: Selenium tests

on:
  workflow_dispatch:
    inputs:
      grid_url:
        required: true
        type: string
        description: Grid to run tests on (local by default)
        default: http://localhost:4444

env:
  CHROME_GRID_IMAGE: selenium/standalone-chrome:131.0-chromedriver-131.0-grid-4.27.0-20250101
  FIREFOX_GRID_IMAGE: selenium/standalone-firefox:133.0-geckodriver-0.35-grid-4.27.0-20250101

jobs:
  Test:
    runs-on: ubuntu-latest
    name: ${{ matrix.browser }}
    strategy:
      fail-fast: false
      matrix:
        browser: [ "chrome", "firefox" ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Launch a standalone grid
        if: ${{ contains(github.event.inputs.grid_url, 'localhost') }}
        run: |
          if [ "${{ matrix.browser }}" = "chrome" ]; then
              IMAGE=$CHROME_GRID_IMAGE
          elif [ "${{ matrix.browser }}" = "firefox" ]; then
              IMAGE=$FIREFOX_GRID_IMAGE
          else
              echo "invalid browser"
              exit 1
          fi
          
          docker run --name grid_container -d -p 4444:4444 --shm-size=2gb $IMAGE

      - name: Run Tests
        env:
          BROWSER: ${{ matrix.browser }}
          GRID_URL: ${{ github.event.inputs.grid_url }}
        run: |
          mvn -q test

      - name: Tear down grid if exists
        if: always()
        run: | 
          docker stop grid_container || true
